name = "anixops-blog"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

# 配置你的自定义域名
# routes = [
#   { pattern = "blog.anixops.com", custom_domain = true }
# ]
